// Generated by FlutterFire CLI — replace ALL placeholder values with your
// actual Firebase project configuration from the Firebase console or by
// running: flutterfire configure
//
// How to get real values:
//   1. Go to https://console.firebase.google.com
//   2. Create / select your project
//   3. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   4. Run: flutterfire configure
//      This will overwrite this file with correct values automatically.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Web ────────────────────────────────────────────────────────────────────
  // TODO: Replace with values from Firebase Console → Project Settings → Web app
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:000000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  // ─── Android ────────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPp5pepXq2gli4gC7dQ2QK_MRnopc89aw',
    appId: '1:998139226130:android:3e7dee1490ef44e1d090cb',
    messagingSenderId: '998139226130',
    projectId: 'medical-bf74c',
    storageBucket: 'medical-bf74c.firebasestorage.app',
    androidClientId: '998139226130-2951c9vihj4vvl9k2asltj636vdkrp9v.apps.googleusercontent.com',
  );

  // ─── iOS ────────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-u1J-ABqt4GahVDJ1iqgsG6yTwtTg9E',
    appId: '1:998139226130:ios:67b46ba017d9d509d090cb',
    messagingSenderId: '998139226130',
    projectId: 'medical-bf74c',
    storageBucket: 'medical-bf74c.firebasestorage.app',
    iosBundleId: 'com.medinova.medinovaAi',
    iosClientId: '998139226130-jou64kitl2eu5aqrv6nmsuietpa8hm8a.apps.googleusercontent.com',
  );

  // ─── macOS ──────────────────────────────────────────────────────────────────
  // TODO: Register a macOS app in Firebase Console if needed; using iOS values as fallback
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP-u1J-ABqt4GahVDJ1iqgsG6yTwtTg9E',
    appId: '1:998139226130:ios:67b46ba017d9d509d090cb',
    messagingSenderId: '998139226130',
    projectId: 'medical-bf74c',
    storageBucket: 'medical-bf74c.firebasestorage.app',
    iosBundleId: 'com.medinova.medinovaAi',
  );
}
